# Generated by Django 3.1.2 on 2020-11-08 16:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='context',
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=tinymce.models.HTMLField(),
        ),
    ]
